# Generated by Django 6.0.7 on 2026-08-01 05:24

import apps.families.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='family name')),
                ('family_code', models.CharField(db_index=True, default=apps.families.models.generate_family_code, max_length=10, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.families.models.family_logo_path)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.families.models.family_cover_path)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_families', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'family',
                'verbose_name_plural': 'families',
                'db_table': 'families',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['family_code'], name='families_family__3f5304_idx'), models.Index(fields=['uuid'], name='families_uuid_adde25_idx')],
            },
        ),
    ]
