# Generated by Django 6.0.7 on 2026-08-04 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('PARENT', 'Parent'), ('SPOUSE', 'Spouse'), ('SIBLING', 'Sibling')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_relationships', to=settings.AUTH_USER_MODEL)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='membership.familymembership')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='membership.familymembership')),
            ],
            options={
                'verbose_name': 'relationship',
                'verbose_name_plural': 'relationships',
                'db_table': 'family_tree_relationships',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_member'], name='family_tree_from_me_a5e049_idx'), models.Index(fields=['to_member'], name='family_tree_to_memb_90cc45_idx'), models.Index(fields=['relationship_type'], name='family_tree_relatio_851d70_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_member', models.F('to_member')), _negated=True), name='relationship_cannot_self_reference'), models.UniqueConstraint(fields=('from_member', 'to_member', 'relationship_type'), name='unique_relationship_pair_per_type')],
            },
        ),
    ]
