# Generated by Django 6.0.7 on 2026-08-01 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0002_alter_family_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('SUPER_ADMIN', 'Super Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='families.family')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'family membership',
                'verbose_name_plural': 'family memberships',
                'db_table': 'family_memberships',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['family'], name='family_memb_family__23cc29_idx'), models.Index(fields=['role'], name='family_memb_role_c02713_idx')],
            },
        ),
    ]
